name: Publish to npmjs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: bun run build

      - name: Publish
        run: bun publish --access public
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
